### ISSUE TITLE
Don't highlight sidebar group buttons in blue

### ISSUE THREAD

**Issue by photron** [Tinkerforge/esp32-firmware#137]
Those do not represent an actual subpage and should be be involved in highlighting at all.

**Comment by rtrbt** [comment]
¯\_(ツ)_/¯

**Comment by photron** [comment]
Closed because the behaviour is not reproducible anymore.

**Comment by rtrbt** [comment]
Still happens, but only on mobile browsers. Use https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover to disable hover effect for sidebar groups.
