### ISSUE TITLE
Make web interface a PWA.

### ISSUE THREAD

**Issue by rtrbt** [Tinkerforge/esp32-firmware#183]
See https://medium.com/@firt/dont-use-ios-web-app-meta-tag-irresponsibly-in-your-progressive-web-apps-85d70f4438cb
https://web.dev/customize-install/#updating-your-apps-icon-and-name
https://web.dev/manifest-updates/#cr-android

Features that we want:
- apple-mobile-web-app-capable https://www.tinkerunity.org/topic/9695-warp-app/#comment-47290 
- app/splash screen icons (can we embed those on Android?)
- controlling the app name -> set to the device display name if it changes

**Comment by ffreddow** [comment]
Was done with f985e5d73e711ef1354283d7488c6a16f2c83c98
