### ISSUE TITLE
Implement PDF export for charge log

### ISSUE THREAD

**Issue by borg42** [Tinkerforge/esp32-firmware#189]
Some accounting departments only accept a charge log in the form of PDF (since from their perspective a CSV is editable while a PDF is not).

Maybe we can add a "download as PDF" function to the charge tracker site that first renders the charge log as a single webpage (which can be printed directly from the browser if desired) and then uses jsPDF or similar to render the HTML into a PDF.

The document should look "official", with the WARP logo, charge ID, location/address, period etc in the header.

**Comment by ffreddow** [comment]
Added with 1217226613fc9b20f437936811db123191d87aee.
