### ISSUE TITLE
WARP: add charging stop condition (timer, energy charged) 

### ISSUE THREAD

**Issue by batti** [Tinkerforge/esp32-firmware#194]
The idea is to add a condition which stops charging the car. For example a timer: "I want to charge for 3 hours" or in case of a WARP2 Charger Pro a condition: "I want to charge 20kWh in my car".

**Comment by m1lk0** [comment]
I was on fire when I read about that most relevant feature for me. With 2.1 I had wished to see that feature within warp. Any chance to push that feature?

**Comment by ffreddow** [comment]
Feature is functional with commit 271ae68562744c84cd297d025c976722270a0ce2.
