### ISSUE TITLE
Charge log: Repair charges that miss the charge end because of a power cycle

### ISSUE THREAD

**Issue by rtrbt** [Tinkerforge/esp32-firmware#213]
A tracked charge with a valid meter_start value (not NAN) but with a meter_end value of 0 or NAN and a duration of 0 seconds is one, where the charger power cycled while charging. Because of https://github.com/Tinkerforge/esp32-firmware/issues/209, such charges exist in the wild.
We can fix those if the next charge has a valid meter_start value.

**Comment by ffreddow** [comment]
Fixed with d06689433ee70958d790ddfe428f832a02dd21f0 and b606182e65405896e6c6184e70e1a1e38c65a1f1
