### ISSUE TITLE
AP config fails with subnet CIDR > 28 || CIDR < 24

### ISSUE THREAD

**Issue by MattiasTF** [Tinkerforge/esp32-firmware#214]
AP config front-end allows CIDR 1-32, but values > 28 or < 24 make WiFiAPClass::softAPConfig() fail.

STA config is not affected. It accepts all CIDR values.

**Comment by ffreddow** [comment]
Done with 8aba99b87fe2f7fce123d307b679a4dd1c07a2f1 and 5065270af57a36b3a39ab5ae3071cfc3de85ee5d.
