### ISSUE TITLE
modbus_tcp: Add last seen NFC tag registers. Allows implementing auth via modbus.

### ISSUE THREAD

**Issue by rtrbt** [Tinkerforge/esp32-firmware#227]
To decide:
- Clear registers if tag_seen > for example 30 seconds? Maybe both a self-clearing and a permanent set of registers?
- Add LED control and/or a register to signal the charger that a tag was seen and accepted/not accepted

**Comment by ffreddow** [comment]
fixed with e9f59055c642cf1c783c207531774bf3bd921dea
