### ISSUE TITLE
MQTT Autodiscover Homeassistant - Konfigurierter Ladestrom

### ISSUE THREAD

**Issue by bbr111** [Tinkerforge/esp32-firmware#230]
im Error log wird diese Meldung angezeigt.

Invalid value for number.konfigurierter_ladestrom: 0 (range 6000.0 - 32000.0)

Wenn Homeassistant startet. Der konfigurierte Ladestrom wird kurz danach auf 6000 gesetzt.
Es sieht aber so aus al ob er mit 0 initialisiert wird.

**Comment by MattiasTF** [comment]
Anscheinend kann das passieren, wenn die Option „Externe Steuerung“ deaktiviert ist oder für das Topic „warp2/ABC/evse/external_current_update“ eine Nachricht mit „retained“ Flag auf dem MQTT-Server liegt. Mit der nächsten Firmware wird das Feld zum Einstellen des Ladestroms in Homeassistant ausgeblendet, wenn „Externe Steuerung“ deaktiviert ist. Die Fehlermeldung wird trotzdem im Log stehen, wenn auf dem MQTT-Server eine retained Nachricht mit Strom 0 liegt.

**Comment by rtrbt** [comment]
Fixed with https://github.com/Tinkerforge/esp32-firmware/commit/94a03a5c106d5c6a4e54933410311f734a0d073c
