### ISSUE TITLE
wrong localized number in chrome

### ISSUE THREAD

**Issue by breitsi** [Tinkerforge/esp32-firmware#236]
My up to date chrome userAgent give me this string:
`navigator.userAgent =>"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"`

in your statement, chrome use the "false" case  
```
return navigator.userAgent.indexOf("Gecko/") >= 0
                ? util.toLocaleFixed(x, digits)
                : (x).toFixed(digits);

```
the result isn't a localized number

https://github.com/Tinkerforge/esp32-firmware/blob/3933d22a1c335f29b6e8a2d932778d70beaba8ce/software/web/src/ts/components/output_float.tsx#L39

**Comment by rtrbt** [comment]
Fixed with [2c8c2e4](https://github.com/Tinkerforge/esp32-firmware/commit/2c8c2e4ab1bd20e3c59320d8a814b077099715e1). Thank you!
