### ISSUE TITLE
Implement NTP time sync. Also support the RTC Bricklet for chargers that can't reach NTP servers.

### ISSUE THREAD

**Issue by rtrbt** [Tinkerforge/esp32-firmware#26]

**Comment by kaeferfreund** [comment]
Das wäre wirklich fein 👍

**Comment by jensstark** [comment]
RTC backup is also important if Internet is down and you want to create charging records.
Would buy immediately. :D

**Comment by rtrbt** [comment]
Fixed with 5e22212 to c73ea33
