### ISSUE TITLE
Module dependencies: Using the dependencies header in a header pulls in additional dependencies.

### ISSUE THREAD

**Issue by MattiasTF** [Tinkerforge/esp32-firmware#267]
Commit fec76c68147c9c71a80ce8fffe46a11bc9fc05bd allows including the dependencies header in other headers, which results in those dependencies getting pulled into all modules that depend on this module. At the moment, this is intended to be used for modules that support cron functions but need to know whether or not the cron module is available.

Investigate alternatives to avoid the extra dependencies and possible circular inclusions.

**Comment by rtrbt** [comment]
Fixed with https://github.com/Tinkerforge/esp32-firmware/commit/b84f152396ce004ac4e27733bb7489641a99bda1
