### ISSUE TITLE
ip_configuration: Check that entered IP and gateway are not the network (first) or broadcast (last) address in the selected subnet (except in /31 networks).

### ISSUE THREAD

**Issue by rtrbt** [Tinkerforge/esp32-firmware#273]
https://en.wikipedia.org/wiki/Internet_Protocol_version_4#First_and_last_subnet_addresses

**Comment by ffreddow** [comment]
fixed with a30caeba8b1c8f5cb74e9e4f15b70217a681bf74 and 0fd1a0d607c499d94bfc161e9f9ec61af4ef13fd.
