### ISSUE TITLE
cron: Add "with global topic prefix" checkbox to MQTT triggers.

### ISSUE THREAD

**Issue by rtrbt** [Tinkerforge/esp32-firmware#275]
Currently a configured trigger for the topic abc/def is triggered if a message is received on both warp2/uid/abc/def and abc/def. Add a checkbox to choose between the topic with or without prefix and only subscribe to one variant per rule.

**Comment by ffreddow** [comment]
fixed with fcfb9e9bfd86da2cd550ce9e162e19b71cc1af45 and fcfb9e9bfd86da2cd550ce9e162e19b71cc1af45
