### ISSUE TITLE
Add SSL/TLS support for the web ui and HTTP API and support for MQTTS

### ISSUE THREAD

**Issue by janknieling** [Tinkerforge/esp32-firmware#293]
It will be very nice to have SSL/TLS support for the web GUI (and the HTTP API) of the WARP chargers and WARP energymanager.
In my opinion it it doesn't makes sense to have an admin login/password protection for the UI and no SSL/TLS to prevent MITM attacks.
Letsencrypt will be nice but a self signed certificate should be sufficient.

Support for MQTT over TLS (MQTTS) will be very nice too for improved security.

**Comment by photron** [comment]
Yes, this is already on the todo list, see issues #76 and #25.
