### ISSUE TITLE
Allow charging a set amount of energy.

### ISSUE THREAD

**Issue by rtrbt** [Tinkerforge/esp32-firmware#32]
When auto-start is disabled, add something to i.e. allow charging 30 kWh and then stopping automatically.

**Comment by m1lk0** [comment]
Hey tinkerforge guys 🥇 
knowing about the energy meter device I would see time based charging (https://github.com/Tinkerforge/esp32-firmware/issues/52) as well as energy volume based charging as must haves for warp2. Would like to see them included soon.

**Comment by rtrbt** [comment]
Fixed (duplicate of #194)
