### ISSUE TITLE
Add config option to change the power-up default value of evse/auto_start_charging

### ISSUE THREAD

**Issue by photron** [Tinkerforge/esp32-firmware#80]
By default evse/auto_start_charging is always enabled after power-up. This is unwanted in certain situations.

https://www.tinkerunity.org/topic/6779-ladestart-nur-durch-mqtt-oder-http

Original issue: Tinkerforge/warp-charger#15

**Comment by rtrbt** [comment]
Fixed with the EVSE slot API.
