### ISSUE TITLE
evse_v2.ts: Argument of type 'boolean' is not assignable to parameter of type 'string | number | string[]

### ISSUE THREAD

**Issue by stif** [Tinkerforge/esp32-firmware#83]
I just tried to compile the esp32-firmware and came along this small error. i guess it is no big deal as it is compiling anyway, but just letting you know.. (maybe a problem for the webpage?)
```
[17:45:43] [TypeScript error: /home/stif/workspace/tinkerforge/esp32-firmware/software/web/src/ts/modules/evse_v2.ts(291,41): Error TS2345: Argument of type 'boolean' is not assignable to parameter of type 'string | number | string[] | ((this: HTMLElement, index: number, value: string) => string)'.] {
  fileName: '/home/stif/workspace/tinkerforge/esp32-firmware/software/web/src/ts/modules/evse_v2.ts',
  line: 291,
  column: 41
}
```

this is the function:
```
function update_evse_button_configuration(b: EVSEButtonConfiguration) {
    $('#evse_button_configuration').val(b.button);
}
```

By the way i am very impressed by the code 👏 (and still try to understand how all this works together 🙈)

**Comment by rtrbt** [comment]
Thanks for the reminder, the button configuration was for some reason still declared as a boolean.

> By the way i am very impressed by the code
Thank you :)

> and still try to understand how all this works together

As a bit of an overview:
- The modules in software/modules/backend are compiled in depending on whether they are listed in the platformio.ini. We use a bit of python (the pio_hooks.py) to generate the main.cpp file for each firmware.
- All modules have the same interface (only by convention): Arduino style setup() and loop() functions, a register_urls() function, that registers APIs (for the web server as well as MQTT), and a bool initialized that is set by setup().
- A good point to start looking into the code structure is the generated main.cpp file (you have to compile the firmware for it to be generated). 
- Also take a look at some simple modules such as the debug, or ethernet module.
